<a href="https://colab.research.google.com/github/Sumanth-Raj-Analyst/skills-introduction-to-github/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

#creation of array:

syntax: np.array(var/value)

In [ ]:
l=[10,20.5,3+4j,True]
arr=np.array(l)
print(arr)

print(type(arr))

type(arr[2])

[10. +0.j 20.5+0.j  3. +4.j  1. +0.j]
<class 'numpy.ndarray'>


numpy.complex128

In [ ]:
# l1=[10,20,30.5,True,{12,36},{"Name":"python","Score":90}]

# l1[4]
# l1[5]["Name"]="Java"

# d={"Name":"python","Score":90}
# d.keys()

l2=[[10,12],(10,20.5),[20.5,10]]
np.array(l2)


array([[10. , 12. ],
       [10. , 20.5],
       [20.5, 10. ]])

2. Checking Dimensions:

syntax: arr_var.ndim

In [ ]:
brr=np.array([10,20,30.5])
brr.ndim

1

2.1: Creation of Bi or Multi-dimensional array:

2-d: arr1=np.array([[10,20,30],[10.5,30,40]])

In [ ]:
set1=set([1,2,3])
set1
arr3=np.array(set1)
type(arr3)

tup=(10,20,30)
arr4=np.array(tup)
arr4


array([10, 20, 30])

In [ ]:
arr1=np.array([[10,20,30],[10.5,30,40]])
arr1



array([[10. , 20. , 30. ],
       [10.5, 30. , 40. ]])

In [ ]:
arr5=np.array([[[10,12],[12,24]],[[25,31],[25,30]]])
print(arr5)
arr5.shape


[[[10 12]
  [12 24]]

 [[25 31]
  [25 30]]]


(2, 2, 2)

3. shape: It is used to find the no of rows and columns present in your array.

syntax: arr_var.shape

In [ ]:
arr1.shape

arr5.shape

(2, 2, 2)

4. reshape: it is used to change the numnber of rows and columns in the existing array.

In [ ]:
arr1.shape

arr1.reshape(3,2)

arr5.reshape(-1)

array([10, 12, 12, 24, 25, 31, 25, 30])

5. arange(): it is used to create the sequence of integers between the provided limit.

syntax: np.arange(starting value, ending value, updation)

In [ ]:
a=np.arange(45,95,2)
a

array([45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77,
       79, 81, 83, 85, 87, 89, 91, 93])

6.linspace(): syntax: np.linspace(SV, EV, UP)

In [ ]:
np.linspace(10,100,20)

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

7. randint(): np.random.randint(sv,ev,n)

In [ ]:
arr5=np.random.randint(10,20,20)
arr5

array([17, 10, 18, 18, 13, 10, 18, 15, 12, 19, 17, 13, 13, 15, 18, 10, 13,
       14, 11, 18])

8. rand(): syntax: np.random.rand()

In [ ]:
arr6=np.random.rand()
arr6

0.8021919197028097

9. randn(): syntax: np.random.randn(n)

In [ ]:
arr6=np.random.randn(10)
arr6

array([ 1.04084022, -0.55752899, -1.95473811,  0.57519988,  1.01654185,
       -1.5988889 ,  0.53262672, -0.06792132, -0.28149285, -0.37108491])

10. copy():

In [ ]:


arr7=np.array(a)
print(arr7)
print(id(arr7))
brr=arr7.copy()
print(brr)
print(id(brr))

arr7[2]=40
arr7

brr

[45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91
 93]
135765076579728
[45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91
 93]
135765076578960


array([45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77,
       79, 81, 83, 85, 87, 89, 91, 93])

11. view()

In [ ]:
a=[10,20.5,True,6+4j]

arr8=np.array(a)
print(arr8)
arr8[2]=5+4j
print(arr8)
print(id(arr8))

brr=arr8.view()
print(brr)
print(id(brr))

[10. +0.j 20.5+0.j  1. +0.j  6. +4.j]
[10. +0.j 20.5+0.j  5. +4.j  6. +4.j]
135765079557776
[10. +0.j 20.5+0.j  5. +4.j  6. +4.j]
135765076579632


In [ ]:
a=[10,{20.5,30},{"Name":"A","Roll":10},20.5,True,3+4j]

arr9=np.array(a)
# print(arr9)
arr9[2]["Name"]="B"
print(arr9)

brr2=arr9.copy()
print(brr2)

[10 {20.5, 30} {'Name': 'B', 'Roll': 10} 20.5 True (3+4j)]
[10 {20.5, 30} {'Name': 'B', 'Roll': 10} 20.5 True (3+4j)]


In [ ]:
a=[10,{20.5,30},{"Name":"A","Roll":10},20.5,True,3+4j]

arr10=np.array(a)
print(arr10)

arr10[2]["Roll"]=15
print(arr10)

brr=arr10.view()
print(brr)

arr10[2]["Roll"]=20
print(arr10)

print(brr)

[10 {20.5, 30} {'Name': 'A', 'Roll': 10} 20.5 True (3+4j)]
[10 {20.5, 30} {'Name': 'A', 'Roll': 15} 20.5 True (3+4j)]
[10 {20.5, 30} {'Name': 'A', 'Roll': 15} 20.5 True (3+4j)]
[10 {20.5, 30} {'Name': 'A', 'Roll': 20} 20.5 True (3+4j)]
[10 {20.5, 30} {'Name': 'A', 'Roll': 20} 20.5 True (3+4j)]


In [ ]:
arr5=np.arange(1,11,1)
print(arr5)
arr5[4]
print(arr5[-2:-11:-2]) #fetching the odd values
print(arr5[1:11:2]) #fetching the even values

[ 1  2  3  4  5  6  7  8  9 10]
[9 7 5 3 1]
[ 2  4  6  8 10]


In [ ]:
arr6=np.arange(5,50,5)
print(arr6)
print(arr6[::2])
print(arr6[1::2])
print(arr6[7::])
print(arr6[-7::-1])

[ 5 10 15 20 25 30 35 40 45]
[ 5 15 25 35 45]
[10 20 30 40]
[40 45]
[15 10  5]


In [ ]:
arr7=np.array([[5,{10:15},20,25],[30,{45:50},55,60]])
#print(arr7)

print(arr7[1][2])
print(arr7[1][1])
print((arr7[1][1]).keys())
print((arr7[0][1]).values())

55
{45: 50}
dict_keys([45])
dict_values([15])


In [ ]:
arr7=np.array([[5,10,15,20,25],[30,45,50,55,60],[65,70,75,80,85]])
arr7
#print(arr7)

#print(arr7[1,:3])
#print(arr7[0:3:][0:3:1])
#arr7[:][:3]
#arr10=arr7[0, :3]
#arr11=arr7[1, :2]
#np.concatenate((arr10,arr11))
#np.append(arr11,arr10)

array([[ 5, 10, 15, 20, 25],
       [30, 45, 50, 55, 60],
       [65, 70, 75, 80, 85]])

In [ ]:
brr=np.arange(1,6,1)
print(brr)

crr=brr**2 #array with const
crr

[1 2 3 4 5]


array([ 1,  4,  9, 16, 25])

In [ ]:
arr1=np.array([10,20,30,40])
print(arr1.ndim)
arr2=np.array([20,30,40,50])
arr1==arr2

1


array([False, False, False, False])

In [ ]:
arr12=np.arange(1,6,1)
print(arr12)
brr12=arr12.copy()
print(brr)
print()
arr12[3]=6
print(arr12)
brr12

arr15=np.array([10,12.5,{10:15},True])
brr15=arr15.copy()

print()
print(arr15)
print(brr15)

print()
arr15[2][10]=20
print(arr15)
print(brr15)


[1 2 3 4 5]
[1 2 3 4 5]

[1 2 3 6 5]

[10 12.5 {10: 15} True]
[10 12.5 {10: 15} True]

[10 12.5 {10: 20} True]
[10 12.5 {10: 20} True]


In [ ]:
a=[[[10,12,13],[14,15,16],[40,41,42]],[[17,18,19],[20,21,22],[50,52,53]]]
arr=np.array(a)
print(arr)
arr.shape
#


[[[10 12 13]
  [14 15 16]
  [40 41 42]]

 [[17 18 19]
  [20 21 22]
  [50 52 53]]]


(2, 3, 3)

In [ ]:
a=np.arange(5)
a<=3

array([ True,  True,  True,  True, False])